version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - 5432
  backend:
    image: backend
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      args:
        - POSTGRES=postgres:5432
    ports:
      - 50051
    init: true
  proxy:
    image: proxy
    build:
      context: ..
      dockerfile: docker/proxy.Dockerfile
      args:
        - BACKEND=backend:50051
    ports:
      - "8080:8080"
  frontend:
    image: frontend
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      args:
        - ENDPOINT=http://localhost:8080
    ports:
      - "1234:80"
